spring:
  application:
    name: SkyWingsExpress-Server
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/swe_server
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/swe_server
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: reg_client
            client-secret: kDjhKVBZwFcm6et4qJCDN0cXDJUpClQZ
            scope: openid

server:
  port: 8081

jwt:
  token:
    secret: ${jwt_token_secret}
    lifetime: ${jwt_token_lifetime}