spring:
  application:
    name: SkyWingsExpress-Server
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/swe_server
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/swe_server
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID}
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            scope: openid
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/realms/swe_server/broker/google/endpoint
            scope: openid, profile, email

keycloak:
  url: ${KEYCLOAK_URL}
  realm: ${KEYCLOAK_REALM_ID}
  client: ${KEYCLOAK_CLIENT_ID}
  client_secret: ${KEYCLOAK_CLIENT_SECRET}

server:
  port: 8081
